Update pip for the Advanced example (#4)
The Advanced example started failing with:

```bash
$ sematic run --log-level debug --build advanced/main.py -- /advanced/data/message.txt
[...]
Step 7/8 : RUN python3 -c "import sematic" || ( export PYTHONDONTWRITEBYTECODE=1 && pip install --no-cache-dir --ignore-installed --root-user-action=ignore sematic && unset PYTHONDONTWRITEBYTECODE )
---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
---> Running in fd7f33465195
Traceback (most recent call last):

  File "<string>", line 1, in <module>

ModuleNotFoundError: No module named 'sematic'


Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...


no such option: --root-user-action

2023-07-19 05:50:34,624  [ERROR] sematic.plugins.building.docker_builder: Image build error details: '{'code': 2, 'message': 'The command \'/bin/sh -c python3 -c "import sematic" || ( export PYTHONDONTWRITEBYTECODE=1 && pip install --no-cache-dir --ignore-installed --root-user-action=ignore sematic && unset PYTHONDONTWRITEBYTECODE )\' returned a non-zero code: 2'}'
[...]
```

This is caused by the existing Dockerfile resulting in the installation
of `pip` `22.0.2`, which does not support the `--root-user-action`
parameter.

This PR updates the Advanced case Dockerfile to install the latest
version of `pip`.